config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'rovers#index'

  patch 'rovers' => 'rovers#update_position'
  resources :rovers
  # get 'rovers' => 'rovers#index'
  #
  # post 'rovers' => 'rovers#create'
  # get 'rovers/new' => 'rovers#new'
  #
  # get 'rovers/:id/edit' => 'rovers#edit', as: 'edit_rover'
  # patch 'rovers/:id/edit' => 'rovers#update'
  #
  # get 'rovers/:id' => 'rovers#show', as: 'rover'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rover.rb
class Rover < ApplicationRecord

  @current_y = 0
  @current_x = 0
  @current_direction = ""
  def read_instruction(position,newmove)

    @current_x = position[0].to_i
    @current_y = position[1].to_i
    @current_direction = position[2].upcase

    moves = newmove

    l = 0
    while l < moves.length

      if moves[l] != "M"
        turn(moves[l])
      else
        move
      end

    l +=1

    end

    return future_position

  end

  def move

        case @current_direction
        when "N"
          @current_y += 1
        when "E"
          @current_x += 1
        when "S"
          @current_y -= 1
        when "W"
          @current_x -= 1
        end

  end

  def turn(n)
    direction_spell = "WNESWN"
    substring_index = direction_spell[1..-2].index(@current_direction)
    position = 1
    position = -1 if n == "L"
    @current_direction = direction_spell[substring_index + 1 + position]
  end

  def future_position
  "#{@current_x}#{@current_y}#{@current_direction}"
  end
#
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rovers_controller.rb
class RoversController < ApplicationController


  def index
    @rovers = Rover.all
    @rovers_qty = @rovers.length
    @rover1 = Rover.find(1)
    @rover1_position = @rover1.current_position
    @rover1_coordination = @rover1_position[0, 2]
    @rover1_direction = @rover1_position[2]

  end

  def show
    set_rover
    @rover_position = @rover.current_position
    @rover_coordination = @rover_position[0, 2]
    @rover_direction = @rover_position[2]

  end

  def new
    @rover = Rover.new
  end

  def create
    @rover = Rover.new(rover_params)
    if @rover.save
      redirect_to rovers_url
    else
      render :new
    end

  end

  def edit
    set_rover
  end

  def update
    set_rover
    if @rover.update_attributes(rover_params)
      redirect_to rovers_url
    else
      render :edit

    end
  end

  def update_position
    @rover1 = Rover.find(1)
    hash = rover_params
    hash[:current_position] = @rover1.read_instruction(hash[:current_position],hash[:move])
    if @rover1.update_attributes(hash)
      render rovers_url
    else
      render rovers_url

    end
  end

  def destroy
  set_rover
  @rover.destroy
  redirect_to rovers_url
  end

  private
    def set_rover
      @rover = Rover.find(params[:id])
    end

    def rover_params
      params.require(:rover).permit(:current_position, :move)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rovers_helper.rb
module RoversHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rover Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rovers/edit.html.erb
<div class="edit_rover">
  <h1>Edit rover #<%=@rover.id%> profile</h1>

  <p>
    <%= link_to "Back", @rover %>
  </p

  <%= form_for @rover do |f| %>
    <p>
      <%= f.label :current_position%> <br>
      <%= f.text_field :current_position%>
    </p>

    <p>
      <%=f.label :move%> <br>
      <%=f.text_field :move%>
    </p>

    <p>
      <%= f.submit "Update"%>
    </p>
  <%end%>
</div>

app/views/rovers/index.html.erb
<div id="titles">
  <h1 class="index-header">Welcome to the Mars Rover game!</h1>

  <!-- <% if @rovers_qty < 1 %>
    <h2 class="index-rover-qty"> Currently there is no rover in the mission</h2>
  <% elsif @rovers_qty > 1 %>
    <h2 class="index-rover-qty">Currently there are <%=@rovers_qty%> rovers in the mission.</h2>
  <%else%>
    <h2 class="index-rover-qty">Currently there is 1 rover in the mission.</h2>
  <%end%> -->

  <!-- <% @rovers.each do |rover| %>
    <%=link_to "Rover #{rover.id} is at: #{rover.current_position}",rover,class:"link_to_rover"%>
  <% end %> -->

  <!-- <%= link_to "Deploy new rover", new_rover_url, class:"link_to_new"%> -->

    <div id="mars">


      <table class="map">
      <!-- create top horizontal table header -->
        <th>Y\X</th>
        <%(0..10).each do |num|%>
          <th> <%=num%> </th>
        <% end %>
        <th>X/Y</th>


        <%(0..10).each do |row|%>
          <tr>
            <td><%= (10 - row) %></td>
            <%(1..11).each do |column|%>
              <%if (@rover1_coordination[0].to_i == (column-1) && @rover1_coordination[1].to_i == (10-row)) %>
                <td id="rover"><%=@rover1_direction%></td>
              <%else%>
                <td class="empty_table">W</td>
              <%end%>
            <%end%>
            <td><%= (10 - row) %></td>
          </tr>
        <%end%>

        <th>Y/X</th>
        <%(0..10).each do |num|%>
          <th> <%=num%> </th>
        <% end %>
        <th>X\Y</th>


      </table>

    </div>
    <div id="player_move">
    <%= form_for @rover1 do |f|%>
      <p>
        <%= f.label "Start position:" %>
        <%= f.text_field :current_position %>
      </p>
      <p>
        <%= f.label "Next move:"%>
        <%= f.text_field :move %>
        <%= f.submit "Go!"%>
      </p>

    <%end%>
    </div>

</div>

app/views/rovers/new.html.erb
<div class="new_rover">
  <h1>Add a new rover</h1>
  <%=link_to "Back to Rover Game", rovers_url %>

  <%= form_for @rover do |f| %>
    <p>
      <%= f.label :current_position%> <br>
      <%= f.text_field :current_position%>
    </p>

    <p>
      <%=f.label :move%> <br>
      <%=f.text_field :move%>
    </p>

    <p>
      <%= f.submit "Save" %>
    </p>
  <%end%>

<div/>

app/views/rovers/show.html.erb
<div class="rover_profile">
  <h1>Rover #<%=@rover.id%> profile</h1>
  <h2>Current position:</h2>
    <h3>X: <%=@rover_coordination[0]%></h3>
    <h3>Y: <%=@rover_coordination[1]%></h3>
  <h2>Current heading direction: <%=@rover_direction %></h2>
  <%= link_to "Back to the Rover Game",rovers_url %> | <%=link_to "Edit", edit_rover_path(@rover)%> | <%=link_to "Delete", @rover, method: :delete, data: {confirm: "Are you sure you want to delete this rover?"}  %>
<div/>